---
- name: Log in (obtain access token)
  redhat.openshift.openshift_auth:
    username: "{{ ocp_auth_openshift_username }}"
    password: "{{ ocp_auth_openshift_password }}"
  register: openshift_auth_results

- name: Set token fact
  set_fact:
    ocp_auth_api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"